Add Address module to parse IP addresses
Thegaram/serfrpc.ml pull request #3
Opened 2018-05-08 08:52 UTC by vinczedani

2018-05-08 11:04 UTC, Thegaram requested changes

2018-05-08 11:04 UTC, Thegaram commented on serfrpc/common.ml
> +  let to_string t =
Let's use `string.concat` for this.

2018-05-08 11:04 UTC, Thegaram commented on serfrpc/common.ml
> +    with e -> print_endline (Printexc.to_string e);
It would be better to throw an exception here.

2018-05-08 11:04 UTC, Thegaram commented on serfrpc/common.ml
> +    Msgpck.of_string "TODO"
Would throwing an exception here work? We don't want others to call unimplemented functions.

2018-05-08 11:04 UTC, Thegaram commented on serfrpc/io.ml
> +    with e -> print_endline (Printexc.to_string e);
I think it would be better to catch these exceptions inside `read_loop` and call the provided `error_handler` with the error message.

2018-05-08 11:04 UTC, Thegaram commented on test/test.ml
> +    let print_addr (member: Serfrpc.Response.Members.member) =
I'm not sure we need to specify the type for `member` here, omitting it might make reading to code easier.

2018-05-09 11:07 UTC, vinczedani commented on test/test.ml
> +    let print_addr (member: Serfrpc.Response.Members.member) =
When omitting it, I get the following error:
```
File "test/test.ml", line 31, characters 61-65:
Error: Unbound record field addr
Makefile:2: recipe for target 'build' failed
make: *** [build] Error 1

```

2018-05-09 11:43 UTC, Thegaram requested changes
Thanks! As I suggested, let's catch exceptions from callbacks inside `read_loop` and call the provided error handler function.

2018-05-09 11:43 UTC, Thegaram commented on serfrpc/io.ml
> +  let header_size = Msgpck.size header in
This Msgpck API change is unreleased. It would be nice to a) pin the correct version in the Makefile or b) specify the required library version in the opam file.

2018-05-09 11:43 UTC, Thegaram commented on test/oUnit/jbuild
> +(executable
Please use the standard indentation for jbuild files.

2018-05-10 08:05 UTC, Thegaram commented on serfrpc/io.ml
> +  let header_size = Msgpck.size header in
@vinczedani I'd suggest let's just keep the old version for now and create a new PR once the new Msgpck version is released.

2020-03-20 13:36 UTC, vinczedani commented
Closing this PR, as its a bit outdated.

2020-03-20 13:36 UTC, closed without merging